---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinsk8s
  labels:
    app: jenkinsk8s
spec:
  selector:
    matchLabels:
      app: jenkinsk8s
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkinsk8s
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: jenkinsk8s
        image: 192.168.152.128/dev/jenkinsk8s_image:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /logs
          name: logs-volume
      imagePullSecrets:
      - name: mysecret
      volumes:
      - name: logs-volume
        hostPath:
          path: /opt/kubernetes/volume/jenkinsk8s
---
apiVersion: v1
kind: Service
metadata:
  name: jenkinsk8s
  labels:
    name: jenkinsk8s
spec:
  ports:
  - port: 80
    name: j-k
    targetPort: 8021
  selector:
    app: jenkinsk8s
