apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkinsk8s
  labels:
    app: jenkinsk8s
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: jenkinsk8s
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: jenkinsk8s
        image: 47.94.159.51/dev/jenkinsk8s_image:0.0.1
      imagePullSecrets:
      - name: docker-secret

---
apiVersion: v1
kind: Service
metadata:
  name: jenkinsk8s
  labels:
    name: jenkinsk8s
spec:
  ports:
  - port: 80
    name: j-k
    targetPort: 8021
  selector:
    name: jenkinsk8s
